# Generated by Django 5.1 on 2024-11-20 01:43

import api.models.calonkaryawan_models
import api.models.company_models
import api.models.karyawan_models
import api.models.product_models
import datetime
import django.contrib.auth.models
import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=100)),
                ('name_company', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=255)),
                ('desc_emply', models.CharField(max_length=255)),
                ('image', models.ImageField(blank=True, null=True, upload_to=api.models.company_models.openrec_directory_path)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Departement',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nama_department', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='PeriodeGaji',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('status_periode', models.CharField(choices=[('active', 'Active'), ('non_active', 'Non Active')], default=None, max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_name', models.CharField(max_length=100)),
                ('img_product', models.ImageField(blank=True, null=True, upload_to=api.models.product_models.product_directory_path)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('email', models.CharField(max_length=255, unique=True)),
                ('role', models.CharField(choices=[('admin', 'Admin'), ('manager', 'Manager'), ('karyawan', 'Karyawan'), ('calon_karyawan', 'Calon Karyawan')], default=None, max_length=50)),
                ('password', models.CharField(max_length=255)),
                ('username', models.CharField(max_length=100, null=True, unique=True)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='CalonKaryawan',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nik', models.IntegerField()),
                ('nama_karyawan', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=100)),
                ('tempat_lahir', models.CharField(max_length=100)),
                ('tanggal_lahir', models.DateField()),
                ('jenis_kelamin', models.CharField(choices=[('laki_laki', 'Laki Laki'), ('perempuan', 'Perempuan')], default=None, max_length=10)),
                ('agama', models.CharField(max_length=100)),
                ('status', models.CharField(choices=[('kawin', 'Kawin'), ('belum_kawin', 'Belum Kawin')], default=None, max_length=50)),
                ('jumlah_anak', models.IntegerField()),
                ('alamat', models.CharField(max_length=100)),
                ('no_telephone', models.CharField(max_length=12, validators=[django.core.validators.MinLengthValidator(10), django.core.validators.MaxLengthValidator(12), django.core.validators.RegexValidator(code='invalid_number', message='Nomor telepon harus terdiri dari 10 hingga 12 angka.', regex='^\\d{10,12}$')])),
                ('photo', models.ImageField(blank=True, null=True, upload_to=api.models.calonkaryawan_models.user_directory_path)),
                ('ktp', models.FileField(blank=True, null=True, upload_to=api.models.calonkaryawan_models.ktp_upload_path)),
                ('ijazah', models.FileField(blank=True, null=True, upload_to=api.models.calonkaryawan_models.ijazah_upload_path)),
                ('status_wawancara', models.CharField(blank=True, choices=[('diterima', 'Diterima'), ('tidak_diterima', 'Tidak Diterima')], default=None, max_length=20, null=True)),
                ('upload_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='calonKaryawan_profiles', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Karyawan',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nik', models.IntegerField()),
                ('nama_karyawan', models.CharField(max_length=100)),
                ('tempat_lahir', models.CharField(max_length=100)),
                ('jenis_kelamin', models.CharField(choices=[('laki_laki', 'Laki Laki'), ('perempuan', 'Perempuan')], default=None, max_length=10)),
                ('tanggal_lahir', models.DateField()),
                ('agama', models.CharField(max_length=100)),
                ('status', models.CharField(choices=[('kawin', 'Kawin'), ('belum_kawin', 'Belum Kawin')], default=None, max_length=50)),
                ('jumlah_anak', models.IntegerField()),
                ('alamat', models.CharField(max_length=100)),
                ('no_telephone', models.CharField(max_length=12, validators=[django.core.validators.MinLengthValidator(10), django.core.validators.MaxLengthValidator(12), django.core.validators.RegexValidator(code='invalid_number', message='Nomor telepon harus terdiri dari 10 hingga 12 angka.', regex='^\\d{10,12}$')])),
                ('jabatan', models.CharField(blank=True, max_length=100, null=True)),
                ('foto', models.ImageField(blank=True, null=True, upload_to=api.models.karyawan_models.foto_karyawan_directory_path)),
                ('department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='karyawan_profiles', to='api.departement')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='karyawan_profiles', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Kehadiran',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('tanggal', models.DateField()),
                ('informasi_kehadiran', models.CharField(blank=True, max_length=100, null=True)),
                ('jam_masuk', models.TimeField(blank=True, null=True)),
                ('jam_pulang', models.TimeField(blank=True, null=True)),
                ('total_jam_kerja', models.TimeField(blank=True, null=True)),
                ('keterangan_kehadiran', models.CharField(choices=[('sakit', 'Sakit'), ('izin', 'Izin'), ('alpha', 'Alpha'), ('masuk', 'Masuk')], default=None, max_length=50)),
                ('total_jam_lembur', models.TimeField(blank=True, null=True)),
                ('biaya_pengobatan', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('keterangan_sakit', models.TextField(blank=True, null=True)),
                ('keterangan_izin', models.TextField(blank=True, null=True)),
                ('is_approved', models.BooleanField(default=False)),
                ('is_read', models.BooleanField(default=False)),
                ('karyawan', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='kehadirankaryawan', to='api.karyawan')),
            ],
        ),
        migrations.CreateModel(
            name='Pinjaman',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('jumlah_pinjaman', models.DecimalField(decimal_places=2, max_digits=12)),
                ('tanggal_pinjaman', models.DateField(blank=True, null=True)),
                ('tenggat_pinjaman', models.DateField(blank=True, null=True)),
                ('is_approve', models.BooleanField(default=False)),
                ('status_pembayaran', models.BooleanField(default=False)),
                ('karyawan', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pinjamankaryawan', to='api.karyawan')),
            ],
        ),
        migrations.CreateModel(
            name='LaporanGaji',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('tanggal_gaji', models.DateField()),
                ('gaji_mentah', models.DecimalField(decimal_places=2, max_digits=12)),
                ('gaji_total', models.DecimalField(decimal_places=2, max_digits=12)),
                ('jumlah_izin', models.IntegerField()),
                ('jumlah_sakit', models.IntegerField()),
                ('karyawan', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='laporanpenggajian', to='api.karyawan')),
                ('periodegaji', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='laporanpenggajian', to='api.periodegaji')),
                ('pinjaman', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='laporanpenggajian', to='api.pinjaman')),
            ],
        ),
        migrations.CreateModel(
            name='SlipGaji',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('terima_dari', models.CharField(max_length=100)),
                ('nominal_gaji', models.DecimalField(decimal_places=2, max_digits=12)),
                ('untuk_pembayaran', models.CharField(max_length=100)),
                ('Laporan_penggajian', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='slipgaji', to='api.laporangaji')),
                ('karyawan', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='slipgaji', to='api.karyawan')),
            ],
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('tanggal_pembayaran', models.DateField(default=datetime.date.today)),
                ('jumlah_pembayaran', models.DecimalField(decimal_places=2, max_digits=12)),
                ('pinjaman_karyawan', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='transaksipembayaran', to='api.pinjaman')),
            ],
        ),
        migrations.CreateModel(
            name='Tunjangan',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('tunjangan_makan', models.DecimalField(decimal_places=2, max_digits=12)),
                ('tunjangan_kesehatan', models.DecimalField(decimal_places=2, max_digits=12)),
                ('tunjangan_jabatan', models.DecimalField(decimal_places=2, max_digits=12)),
                ('THR', models.DecimalField(decimal_places=2, max_digits=12)),
                ('bonus', models.DecimalField(decimal_places=2, max_digits=12)),
                ('karyawan', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tunjangankaryawan', to='api.karyawan')),
            ],
        ),
        migrations.AddField(
            model_name='laporangaji',
            name='tunjangan',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='laporanpenggajian', to='api.tunjangan'),
        ),
    ]
