# Generated by Django 5.1 on 2024-09-27 06:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Departement',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nama_department', models.CharField(max_length=100)),
            ],
        ),
    ]
