# Generated by Django 5.1 on 2024-10-29 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_user_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='kehadiran',
            name='keterangan_izin',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='kehadiran',
            name='keterangan_sakit',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='kehadiran',
            name='biaya_pengobatan',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AlterField(
            model_name='kehadiran',
            name='informasi_kehadiran',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='kehadiran',
            name='jam_masuk',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='kehadiran',
            name='jam_pulang',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='kehadiran',
            name='keterangan_kehadiran',
            field=models.CharField(choices=[('sakit', 'Sakit'), ('izin', 'Izin'), ('alpha', 'Alpha'), ('masuk', 'Masuk')], default=None, max_length=50),
        ),
        migrations.AlterField(
            model_name='kehadiran',
            name='total_jam_kerja',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='kehadiran',
            name='total_jam_lembur',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
