# Generated by Django 5.1 on 2024-09-27 13:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_departement'),
    ]

    operations = [
        migrations.CreateModel(
            name='Karyawan',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nik', models.IntegerField()),
                ('nama_karyawan', models.CharField(max_length=100)),
                ('tempat_lahir', models.CharField(max_length=100)),
                ('tanggal_lahir', models.DateField()),
                ('agama', models.CharField(max_length=100)),
                ('status', models.CharField(max_length=100)),
                ('jumlah_anak', models.IntegerField()),
                ('alamat', models.CharField(max_length=100)),
                ('no_telpon', models.IntegerField()),
                ('email', models.CharField(max_length=100)),
                ('jabatan', models.CharField(max_length=100)),
                ('foto', models.ImageField(blank=True, null=True, upload_to='foto_karyawan/')),
                ('departement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='karyawan_profiles', to='api.departement')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='karyawan_profiles', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
