# Generated by Django 5.1 on 2024-10-29 13:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_kehadiran_keterangan_izin_kehadiran_keterangan_sakit_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='karyawan',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='karyawan_profiles', to=settings.AUTH_USER_MODEL),
        ),
    ]
