# Generated by Django 5.1 on 2024-09-27 13:50

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_karyawan_jenis_kelamin_alter_karyawan_status'),
    ]

    operations = [
        migrations.RenameField(
            model_name='karyawan',
            old_name='departement',
            new_name='department',
        ),
        migrations.RemoveField(
            model_name='karyawan',
            name='email',
        ),
        migrations.AlterField(
            model_name='karyawan',
            name='no_telpon',
            field=models.CharField(help_text='Phone number must be between 10 to 12 digits and contain only numbers', max_length=12, validators=[django.core.validators.MinLengthValidator(10), django.core.validators.MaxLengthValidator(12), django.core.validators.RegexValidator(message='Phone number must contain only digits.', regex='^\\d+$')]),
        ),
    ]
