# Generated by Django 5.1 on 2024-10-29 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_alter_karyawan_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='calonkaryawan',
            name='status_wawancara',
            field=models.CharField(blank=True, choices=[('diterima', 'Diterima'), ('tidak_diterima', 'Tidak Diterima')], default=None, max_length=20, null=True),
        ),
    ]
