# Generated by Django 5.1 on 2024-10-29 14:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_alter_calonkaryawan_status_wawancara'),
    ]

    operations = [
        migrations.AlterField(
            model_name='karyawan',
            name='department',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='karyawan_profiles', to='api.departement'),
        ),
        migrations.AlterField(
            model_name='karyawan',
            name='jabatan',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
