# Generated by Django 5.1 on 2024-09-27 13:53

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_rename_departement_karyawan_department_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='karyawan',
            name='no_telpon',
            field=models.CharField(max_length=12, validators=[django.core.validators.MinLengthValidator(10), django.core.validators.MaxLengthValidator(12), django.core.validators.RegexValidator(code='invalid_number', message='Nomor telepon harus terdiri dari 10 hingga 12 angka.', regex='^\\d{10,12}$')]),
        ),
    ]
