# Generated by Django 5.1 on 2024-10-31 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_alter_karyawan_department_alter_karyawan_jabatan'),
    ]

    operations = [
        migrations.AddField(
            model_name='kehadiran',
            name='is_approved',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='kehadiran',
            name='is_read',
            field=models.BooleanField(default=False),
        ),
    ]
