# Generated by Django 5.1 on 2024-09-27 13:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_alter_karyawan_no_telpon'),
    ]

    operations = [
        migrations.RenameField(
            model_name='karyawan',
            old_name='no_telpon',
            new_name='no_telephone',
        ),
    ]
