# Generated by Django 5.1 on 2024-09-27 14:26

import api.models.karyawan_models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_rename_no_telpon_karyawan_no_telephone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='karyawan',
            name='foto',
            field=models.ImageField(blank=True, null=True, upload_to=api.models.karyawan_models.user_directory_path),
        ),
    ]
