# Generated by Django 5.1 on 2024-11-03 12:21

import api.models.product_models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_company'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('catagory_name', models.CharField(max_length=100)),
                ('img_product', models.ImageField(blank=True, null=True, upload_to=api.models.product_models.product_directory_path)),
            ],
        ),
        migrations.AddField(
            model_name='company',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='company',
            name='desc_emply',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='company',
            name='description',
            field=models.CharField(max_length=255),
        ),
    ]
