# Generated by Django 5.1 on 2024-09-28 04:44

import api.models.calonkaryawan_models
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_alter_karyawan_foto'),
    ]

    operations = [
        migrations.CreateModel(
            name='CalonKaryawan',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nik', models.IntegerField()),
                ('nama_karyawan', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=100)),
                ('tempat_lahir', models.CharField(max_length=100)),
                ('tanggal_lahir', models.DateField()),
                ('jenis_kelamin', models.CharField(choices=[('laki_laki', 'Laki Laki'), ('perempuan', 'Perempuan')], default=None, max_length=10)),
                ('agama', models.CharField(max_length=100)),
                ('status', models.CharField(choices=[('kawin', 'Kawin'), ('belum_kawin', 'Belum Kawin')], default=None, max_length=50)),
                ('jumlah_anak', models.IntegerField()),
                ('alamat', models.CharField(max_length=100)),
                ('no_telephone', models.CharField(max_length=12, validators=[django.core.validators.MinLengthValidator(10), django.core.validators.MaxLengthValidator(12), django.core.validators.RegexValidator(code='invalid_number', message='Nomor telepon harus terdiri dari 10 hingga 12 angka.', regex='^\\d{10,12}$')])),
                ('photo', models.ImageField(blank=True, null=True, upload_to=api.models.calonkaryawan_models.user_directory_path)),
                ('ktp', models.FileField(blank=True, null=True, upload_to=api.models.calonkaryawan_models.ktp_upload_path)),
                ('ijazah', models.FileField(blank=True, null=True, upload_to=api.models.calonkaryawan_models.ijazah_upload_path)),
                ('status_wawancara', models.CharField(choices=[('diterima', 'Diterima'), ('tidak_diterima', 'Tidak Diterima')], default=None, max_length=20)),
                ('upload_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
