# Generated by Django 5.1 on 2024-11-03 12:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_product_company_is_active_alter_company_desc_emply_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='catagory_name',
            new_name='category_name',
        ),
    ]
