# Generated by Django 5.1 on 2024-09-28 06:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_calonkaryawan'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tunjangan',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('tunjangan_makan', models.DecimalField(decimal_places=2, max_digits=12)),
                ('tunjangan_kesehatan', models.DecimalField(decimal_places=2, max_digits=12)),
                ('tunjangan_jabatan', models.DecimalField(decimal_places=2, max_digits=12)),
                ('THR', models.DecimalField(decimal_places=2, max_digits=12)),
                ('bonus', models.DecimalField(decimal_places=2, max_digits=12)),
            ],
        ),
    ]
