# Generated by Django 5.1 on 2024-11-04 05:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_rename_catagory_name_product_category_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='pinjaman',
            name='is_approve',
            field=models.BooleanField(default=False),
        ),
    ]
