# Generated by Django 5.1 on 2024-09-28 06:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_tunjangan'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pinjaman',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('jumlah_pinjaman', models.DecimalField(decimal_places=2, max_digits=12)),
                ('tanggal_pinjaman', models.DateField()),
                ('tenggat_pinjam', models.DateField()),
            ],
        ),
    ]
