# Generated by Django 5.1 on 2024-09-28 06:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_pinjaman'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pinjaman',
            old_name='tenggat_pinjam',
            new_name='tenggat_pinjaman',
        ),
    ]
