# Generated by Django 5.1 on 2024-11-04 06:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_pinjaman_is_approve'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pinjaman',
            name='tanggal_pinjaman',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='pinjaman',
            name='tenggat_pinjaman',
            field=models.DateField(blank=True, null=True),
        ),
    ]
