# Generated by Django 5.1 on 2024-11-04 06:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_alter_pinjaman_tanggal_pinjaman_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pinjaman',
            name='karyawan',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pinjamankaryawan', to='api.karyawan'),
        ),
    ]
