# Generated by Django 5.1 on 2024-11-04 07:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_pinjaman_karyawan'),
    ]

    operations = [
        migrations.AddField(
            model_name='pinjaman',
            name='status_pembayaran',
            field=models.BooleanField(default=False),
        ),
    ]
