# Generated by Django 5.1 on 2024-09-29 04:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_periodegaji_kehadiran_laporangaji_slipgaji_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kehadiran',
            name='keterangan_kehadiran',
            field=models.CharField(choices=[('sakit', 'Sakit'), ('izin', 'izin'), ('alpha', 'Alpha'), ('masuk', 'Masuk')], default=None, max_length=50),
        ),
    ]
