# Generated by Django 5.1 on 2024-11-05 02:19

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_pinjaman_status_pembayaran'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='tanggal_pembayaran',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
