# Generated by Django 5.1 on 2024-11-05 04:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0015_alter_transaction_tanggal_pembayaran'),
    ]

    operations = [
        migrations.AddField(
            model_name='tunjangan',
            name='karyawan',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tunjangankaryawan', to='api.karyawan'),
        ),
    ]
