from .user_models import User
from .departement_models import Departement
from .karyawan_models import Karyawan
from .calonkaryawan_models import CalonKaryawan
from .tunjangan_models import Tunjangan
from .pinjaman_models import Pinjaman
from .kehadiran_models import Kehadiran
from .laporangaji_models import LaporanGaji
from .periode_models import PeriodeGaji
from .slipgaji_models import SlipGaji
from .transaksi_models import Transaction